theme: jekyll-theme-minimal
title: Ediz Gün'ün Web Sitesi
description: Bilgisayar Mühendisliği öğrencisi Ediz Gün'ün kişisel sayfası.
author: Ediz Gün
theme: jekyll-theme-minimal

# Sosyal medya bağlantıları
twitter_username: edizgun
github_username: EdizGn
linkedin_username: edizgun

# Sayfa başlığı favicon gibi başlıklar için
show_downloads: false

# Navigasyon menüsü
# …diğer ayarlarınız…

navigation:
  - title: Anasayfa
    url: /
  - title: Hakkımda
    url: /about
  - title: Projeler
    url: /projects

markdown: kramdown
kramdown:
  input: GFM

  navigation:
  - title: Anasayfa
    url: /
  - title: Hakkımda
    url: /about

